#!/bin/sh
#author: Nguyen Cong Hai
#created: 2016-07-05
#description: default header template


# # not use emacsclient to get specific COMMENT symbol because:
# # - dependent on emacs for comment symbol -> no need, rather defininng the symbol in each specific mode instead:
# # - this will cause shell-command-to-string in emacs to halt processing, so comment this out:

# set default value for COMMENT if not yet defined:
## if BLOCK_COMMENT_START and BLOCK_COMMENT_END are set, cancel COMMENT and COMMENT_END:
cat <<EOF
$(_v COMMENT) author: Cong Hai Nguyen ; created: $(date +%F)
$(_v COMMENT) version: 0.0.1
$(_v COMMENT) license: GNU GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.txt)
$(_v COMMENT) description:
EOF
