#!/bin/bash
set -o errexit

#define parameters which are passed in.
content="$(xclip -out)"  # this has led to non-halting if run inside emacs before
accessedate="$(date +%F)"
[ -z "$QUOTE_TYPE" ] && QUOTE_TYPE="QUOTE"
## focus on web browser and copy the link:
("${HOME}"/bin/focus web 2>/dev/null) 
xdotool key ctrl+l 
xdotool key ctrl+c 
xdotool key super+Tab
cat << EOF
from [[$(xclip -out)]]. accessed ${accessedate}.
#+BEGIN_${QUOTE_TYPE}
${content}
#+END_${QUOTE_TYPE}
EOF
