#!/bin/sh
#author: Nguyen Cong Hai
#created: 2016-07-05

# ========================= VARIABLES =========================

setVars COMMENT COMMENT_END SEPARATOR REPEAT

HALF_REPEAT=$(($REPEAT/2))

# ========================= OPERATIONS  =========================
:
printf -- "${COMMENT} "
printf -- "%${HALF_REPEAT}s" |tr " " "$SEPARATOR"
printf -- " "
printf -- "%${HALF_REPEAT}s" |tr " " "$SEPARATOR"
printf -- "${COMMENT_END} "
