#!/bin/sh
#author: Nguyen Cong Hai
#created: 2016-07-05

cat << EOF
; imm_retval=\$?
 if [ \$imm_retval -ne 0 ] ; then {
  echo "non-zero exit code \${imm_retval}" >&2
  exit \$imm_retval
 } ; fi
EOF
