#!/bin/bash
#author: Nguyen Cong Hai
#created: 2016-07-05
#description: 

# -*- mode: sh -*-
# name: ops
# key: ops
# author Nguyen Cong Hai
# created 2016-06-15
# --

:
cat << EOF
if [ -z "\${ops}" ] ; then
		echo "improper operation keyword: \${ops}" >&2
  exit 1
fi

case "\${ops}" in
 *) 
  echo "unknown operation keyword: ${ops}" >&2
  exit 1
  ;;
esac
EOF
