#!/bin/sh

cat  << EOF
if [ "\$(whoami)" != 'root' ] ; then {
 nonRootUser="\${USER}"
 # assuming program is invoked not sourced (not yet implementing this assumption in code to preserve simplicity):
 su -c "\${0}"
} ; else {
 read -t 5 -p "You non-root user name: " nonRootUser
 if [ -z "\$nonRootUser" ] ; then {
  echo "invalid username (blank). Quit now." >&2
  exit 1
 } ; fi
} ; fi
EOF
